version: '3.8'

networks:
  global_network:
    external: true

services:
  ap_backend:
    image: 'node:16.15-alpine3.15'
    container_name: ap_backend
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8000"
    networks:
      - global_network
